// This file is generated by Prismic local builder. Update with care!

export { default as CodeBlock } from './CodeBlock'
export { default as MyFirstSlice } from './MyFirstSlice'
export { default as TestSlice } from './TestSlice'
export { default as TestingThis } from './TestingThis'
